version: '3.8'

services:
  # Tinc VPN node service
  earthgrid-tinc:
    image: ghcr.io/adefilippo83/project-earthgrid/earthgrid-tinc:latest
    container_name: earthgrid-tinc
    restart: unless-stopped
    build:
      context: ./earthgrid-tinc
    cap_add:
      - NET_ADMIN
    environment:
      - NODE_NAME=${NODE_NAME:-node1}
      - INTERNAL_VPN_IP=${INTERNAL_VPN_IP:-10.100.1.1}
      - PUBLIC_IP=${PUBLIC_IP:-auto}
      - GPG_KEY_ID=${GPG_KEY_ID}
      - GITHUB_REPO=${GITHUB_REPO:-adefilippo83/project-earthgrid}
      - GITHUB_BRANCH=${GITHUB_BRANCH:-main}
      - MANIFEST_FILENAME=${MANIFEST_FILENAME:-manifest.yaml}
      - ENABLE_AUTO_DISCOVERY=${ENABLE_AUTO_DISCOVERY:-true}
      - SYNC_INTERVAL=${SYNC_INTERVAL:-3600}
      - CONTAINER_TYPE=tinc
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./data/tinc:/etc/tinc
      - ./data/gnupg:/root/.gnupg
      - ./data/logs/tinc:/var/log/earthgrid
      - ./data/manifest-repo:/var/lib/earthgrid/manifest-repo
      - ./data/manifest:/var/lib/earthgrid/manifest
      - ./earthgrid-integration/scripts:/usr/local/lib/earthgrid/integration
    ports:
      - "655:655/udp"
      - "655:655/tcp"
    networks:
      - earthgrid-net
      - default
    secrets:
      - source: gpg_private_key
        target: gpg_private_key

  # Tahoe-LAFS client service (optional, based on node role)
  earthgrid-tahoe-client:
    image: ghcr.io/adefilippo83/project-earthgrid/earthgrid-tahoe-client:latest
    container_name: earthgrid-tahoe-client
    restart: unless-stopped
    build:
      context: ./earthgrid-tahoe-client
    depends_on:
      - earthgrid-tinc
    entrypoint: ["/usr/local/lib/earthgrid/integration/container-startup.sh"]
    environment:
      - NODE_NAME=${NODE_NAME:-node1}
      - CLIENT_PORT=${TAHOE_CLIENT_PORT:-3456}
      - INTRODUCER_FURL=${TAHOE_INTRODUCER_FURL:-}
      - SHARES_NEEDED=${TAHOE_SHARES_NEEDED:-3}
      - SHARES_HAPPY=${TAHOE_SHARES_HAPPY:-7}
      - SHARES_TOTAL=${TAHOE_SHARES_TOTAL:-10}
      - NICKNAME=earthgrid-${NODE_NAME:-node1}-client
      - CONTAINER_TYPE=client
      - DEBUG=${DEBUG:-false}
      - STARTUP_TIMEOUT=${STARTUP_TIMEOUT:-180}
    volumes:
      - ./data/tahoe-client:/var/lib/tahoe-client
      - ./data/logs/tahoe-client:/var/log/earthgrid
      - ./data/manifest:/var/lib/earthgrid/manifest
      - ./earthgrid-integration/scripts:/usr/local/lib/earthgrid/integration
    ports:
      - "${TAHOE_CLIENT_PORT:-3456}:${TAHOE_CLIENT_PORT:-3456}"
    networks:
      - earthgrid-net
    deploy:
      replicas: ${DEPLOY_CLIENT:-0}

  # Tahoe-LAFS storage service (optional, based on node role)
  earthgrid-tahoe-storage:
    image: ghcr.io/adefilippo83/project-earthgrid/earthgrid-tahoe-storage:latest
    container_name: earthgrid-tahoe-storage
    restart: unless-stopped
    build:
      context: ./earthgrid-tahoe-storage
    depends_on:
      - earthgrid-tinc
    entrypoint: ["/usr/local/lib/earthgrid/integration/container-startup.sh"]
    environment:
      - NODE_NAME=${NODE_NAME:-node1}
      - STORAGE_PORT=${TAHOE_STORAGE_PORT:-3457}
      - INTRODUCER_FURL=${TAHOE_INTRODUCER_FURL:-}
      - RESERVED_SPACE=${TAHOE_RESERVED_SPACE:-50G}
      - NICKNAME=earthgrid-${NODE_NAME:-node1}-storage
      - MONITOR_INTERVAL=${TAHOE_MONITOR_INTERVAL:-300}
      - CONTAINER_TYPE=storage
      - DEBUG=${DEBUG:-false}
      - STARTUP_TIMEOUT=${STARTUP_TIMEOUT:-180}
    volumes:
      - ./data/tahoe-storage:/var/lib/tahoe-storage
      - ./data/logs/tahoe-storage:/var/log/earthgrid
      - ${STORAGE_PATH:-./data/storage}:/storage
      - ./data/manifest:/var/lib/earthgrid/manifest
      - ./earthgrid-integration/scripts:/usr/local/lib/earthgrid/integration
    ports:
      - "${TAHOE_STORAGE_PORT:-3457}:${TAHOE_STORAGE_PORT:-3457}"
    networks:
      - earthgrid-net
    deploy:
      replicas: ${DEPLOY_STORAGE:-0}

  # Tahoe-LAFS introducer service (optional, based on node role)
  earthgrid-tahoe-introducer:
    image: ghcr.io/adefilippo83/project-earthgrid/earthgrid-tahoe-introducer:latest
    container_name: earthgrid-tahoe-introducer
    restart: unless-stopped
    build:
      context: ./earthgrid-tahoe-introducer
    depends_on:
      - earthgrid-tinc
    entrypoint: ["/usr/local/lib/earthgrid/integration/container-startup.sh"]
    environment:
      - NODE_NAME=${NODE_NAME:-node1}
      - INTRODUCER_PORT=${TAHOE_INTRODUCER_PORT:-3458}
      - NICKNAME=earthgrid-${NODE_NAME:-node1}-introducer
      - PUBLISH_INTERVAL=${TAHOE_PUBLISH_INTERVAL:-300}
      - MANIFEST_DIR=/var/lib/earthgrid/manifest
      - CONTAINER_TYPE=introducer
      - DEBUG=${DEBUG:-false}
      - STARTUP_TIMEOUT=${STARTUP_TIMEOUT:-180}
    volumes:
      - ./data/tahoe-introducer:/var/lib/tahoe-introducer
      - ./data/logs/tahoe-introducer:/var/log/earthgrid
      - ./data/manifest:/var/lib/earthgrid/manifest
      - ./earthgrid-integration/scripts:/usr/local/lib/earthgrid/integration
    ports:
      - "${TAHOE_INTRODUCER_PORT:-3458}:${TAHOE_INTRODUCER_PORT:-3458}"
    networks:
      - earthgrid-net
    deploy:
      replicas: ${DEPLOY_INTRODUCER:-0}

networks:
  earthgrid-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

secrets:
  gpg_private_key:
    file: ${GPG_KEY_FILE:-./secrets/gpg_private_key.asc}

# This docker-compose file includes:
# 1. The Tinc VPN container for mesh networking
# 2. Tahoe-LAFS containers for distributed storage
#    - Client: For accessing the storage grid
#    - Storage: For contributing storage to the grid
#    - Introducer: For helping nodes discover each other
# 3. An optional management UI for network monitoring and configuration
#
# To run with specific roles:
# DEPLOY_CLIENT=1 DEPLOY_STORAGE=1 DEPLOY_INTRODUCER=0 docker-compose up -d
#
# Integration Variables:
# DEBUG=true - Enable verbose debugging for integration scripts
# STARTUP_TIMEOUT=300 - Increase timeout (in seconds) for container dependencies
# VPN_VALIDATION_RETRIES=60 - Number of retries for VPN validation
# 
# Network Testing:
# TEST_MODE=true docker-compose up -d  - Run in test mode without pushing to GitHub
