name: Validate Pull Request

on:
  pull_request:
    paths:
      - 'tinc/hosts/**'
      - 'tinc/inventory/nodes.yml'
      - 'tahoe/inventory/tahoe-nodes.yml'
      - 'tahoe/config/*.template'
      - 'tahoe/hosts/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Validate configuration
        run: |
          python .github/scripts/validate_pr.py
